import type { ServiceConfig } from "./types";
import {
  ElementPlusSizeEnum,
  HeaderMenuAlignEnum,
  HeaderStyleEnum,
  LanguageEnum,
  LayoutModeEnum,
  MenuThemeEnum,
  PageTransitionEnum,
  SystemThemeEnum,
  TabNavModeEnum,
  ThemePanelTriggerPositionEnum,
  TitleModeEnum,
} from "@/common/enums";

export const defaultServiceConfig: ServiceConfig = {
  layout: {
    name: "Teek Design Pro",
    avatar: "/avatar.png",
    titleMode: TitleModeEnum.ProjectPage,
    layoutMode: LayoutModeEnum.Vertical,
    menuTheme: MenuThemeEnum.Light,
    isDark: false,
    isWeak: false,
    isGrey: false,
    maximize: false,
    watermark: false,
    moreRouteChildrenHideInMenuThenOnlyOne: false,
    tooltipEffect: isDark => (isDark ? "light" : "dark"),
    elementPlusSize: ElementPlusSizeEnum.Default,
    language: LanguageEnum.ZhCn,
    watchFrame: false,
    lockSecretKey: "my-secret-key",
    errorLog: {
      showInHeader: true,
      printConsole: true,
      env: [],
    },
    themePanelTriggerPosition: ThemePanelTriggerPositionEnum.Header,
  },
  tabNav: {
    enabled: true,
    tabNavMode: TabNavModeEnum.Simple,
    showTabNavIcon: true,
    showTabNavDot: true,
    recordTabNav: false,
    fixTabNav: true,
    draggable: true,
    height: 38,
    middleClickToClose: false,
    middleClickToOpen: true,
    showMore: true,
    wheel: true,
  },
  breadcrumb: {
    enabled: true,
    showIcon: true,
    hideOnlyOne: false,
    showHome: true,
    onlyShowHomeIcon: false,
  },
  header: {
    enabled: true,
    style: HeaderStyleEnum.Page,
    height: 55,
    menuAlign: HeaderMenuAlignEnum.Start,
  },
  menu: {
    width: 240,
    accordion: false,
    isCollapse: false,
  },
  theme: {
    primaryColor: "#395AE3",
    radius: 0.75,
    systemThemeMode: SystemThemeEnum.System,
  },
  logo: {
    enable: true,
    source: "/logo.png",
  },
  transition: {
    page: PageTransitionEnum.SlideLeft,
    progress: true,
  },
  router: {
    whiteList: [""],
    routeUseI18n: true,
    nameI18nPrefix: "_route",
    isKeepAlive: false,
    isFull: false,
    cacheDynamicRoutes: false,
    routeUseTooltip: false,
  },
  cache: {
    cacheKeyPrefix: "teek",
    tabNavCacheKey: "tabNav",
    cacheDynamicRoutesKey: "dynamicRoutes",
    versionCacheKey: "version",
    tabExcludesUrlKey: ["layoutMode"],
    cleanCacheWhenUpgrade: false,
  },
} as ServiceConfig;
